spring.application.name=Dimetyd_Amazon_Bot



# default properties
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=true
spring.datasource.tomcat.max-wait=10000
spring.datasource.hikari.maximum-pool-size=5
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.profiles.active=production



bucketname = com.threecolts.us-east-1.dimetyd.screenshots.prod
region = us-east-1
secret.name = arn:aws:secretsmanager:us-east-1:248387103323:secret:/infra/prod/dimetyd/rds-produpstartusadb-y5L4YE
#secret.name = arn:aws:secretsmanager:us-east-1:248387103323:secret:/infra/stage/dimetyd/rds-credentials-Ag9i1X
is_db_local = true